// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bcnofficechallengeapi.Data;

#nullable disable

namespace bcnofficechallengeapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bcnofficechallengeapi.Models.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_pass");

                    b.Property<string>("AppUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_user");

                    b.HasKey("Id");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.Curiosity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sponsor_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId")
                        .IsUnique();

                    b.ToTable("curiosities", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sponsor_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId")
                        .IsUnique();

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "SortOrder");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.RankingEntry", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<DateTime?>("PointsTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("points_timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.ToTable((string)null);

                    b.ToView("ranking", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("PointsValue")
                        .HasColumnType("int")
                        .HasColumnName("points_value");

                    b.Property<Guid>("QrId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("qr_id");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("sponsors", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_title");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("linkedin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<DateTime?>("PointsTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("points_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.UserCuriosityView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sponsor_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("UserId", "SponsorId")
                        .IsUnique();

                    b.ToTable("user_curiosity_views", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.UserSponsorScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("MaximumPoints")
                        .HasColumnType("int")
                        .HasColumnName("maximum_points");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int")
                        .HasColumnName("points_awarded");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("scanned_at");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sponsor_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("UserId", "SponsorId")
                        .IsUnique();

                    b.ToTable("user_sponsor_scans", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.UserSponsorScanAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int")
                        .HasColumnName("points_awarded");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("question_text");

                    b.Property<string>("CorrectOptionIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_option_ids");

                    b.Property<string>("SelectedOptionIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("selected_option_ids");

                    b.Property<Guid>("UserSponsorScanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_sponsor_scan_id");

                    b.HasKey("Id");

                    b.HasIndex("UserSponsorScanId", "QuestionId")
                        .IsUnique();

                    b.ToTable("user_sponsor_scan_answers", (string)null);
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.WeatherForecastRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecastRecords");
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.Curiosity", b =>
                {
                    b.HasOne("bcnofficechallengeapi.Models.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.Question", b =>
                {
                    b.HasOne("bcnofficechallengeapi.Models.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.QuestionOption", b =>
                {
                    b.HasOne("bcnofficechallengeapi.Models.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.UserCuriosityView", b =>
                {
                    b.HasOne("bcnofficechallengeapi.Models.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bcnofficechallengeapi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.UserSponsorScan", b =>
                {
                    b.HasOne("bcnofficechallengeapi.Models.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bcnofficechallengeapi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.UserSponsorScanAnswer", b =>
                {
                    b.HasOne("bcnofficechallengeapi.Models.UserSponsorScan", null)
                        .WithMany("AnswerResults")
                        .HasForeignKey("UserSponsorScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.UserSponsorScan", b =>
                {
                    b.Navigation("AnswerResults");
                });

            modelBuilder.Entity("bcnofficechallengeapi.Models.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
